### ISSUE TITLE
db backup fails to remove old files, leads to full disk and no new backups

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/infrastructure#1305]
The script makes a backup of the database, uploads it to the GenomicsVL object store then deletes older files in both the object store and on the local disk based on what is on the local disk.  This can lead to it trying to delete something that is not in the object store and exiting 1 before it gets to the step of deleting files from the local disk. https://github.com/usegalaxy-au/infrastructure/blob/master/roles/slg.db-backup/templates/galaxy-backup-db.sh.j2#L136

**Comment by cat-bro** [comment]
The new ETCA deployment could be a good place to test the slg.db_backup role.

(1) If there is not a flag in the role such as 'db_backup_create_cron_job', add this and set the cron job creation task to run only when that is true.
(2) With cron job creation set to false, uncomment all other variables and check whether database backup script ends up the same (except for IPs) as the one on aarnet backup
(3) Change the 'swift delete' line so that it does not exit the playbook if it fails.

**Comment by jlqfab** [comment]
the time to run the backup (as cronjob) needs to be modified in `roles/slg.db-backup/defaults/main.yml` to 4am AEST = 18 UTC. This can be done with:
`backup_run_hour: "18" # 18 UTC = 4am AEST; was 23 UTC = 9am AEST`

**Comment by cat-bro** [comment]
The top priority for this issue needs to be to make the 'swift delete' step not cause the playbook to exit. Otherwise we have to keep remembering to delete files manually in order to have backups at all.

**Comment by nuwang** [comment]
How about using an expiration policy as an alternative? Should be less error prone overall I think. https://docs.openstack.org/swift/latest/overview_expiring_objects.html

**Comment by jlqfab** [comment]
Expiration policies don't work for segments. And the backups are segmented.

**Comment by nuwang** [comment]
Are we using a different container for segments? The docs say: "Note that segments will continue to appear in listings and be counted for quotas until they are cleaned up by the object-expirer. This option is only available when all segments are in the same container and none of them are nested SLOs.". 
https://docs.openstack.org/swift/latest/overview_large_objects.html

I've only ever used object expiry with s3, which is pretty straight forward. I don't know much about the nuances of expiry in swift.

**Comment by jlqfab** [comment]
Yes. There is a manifest file and a segment file. Only entries in the manifest file are expired - the segments aren't, and they are what takes up all the space (2G each).

**Comment by jlqfab** [comment]
FYI I solved this in Apollo and would like to adapt the Apollo approach to the Galaxy backups.
See [apollo backup_scripts](https://github.com/AU-Biocommons/genome-annotation/tree/master/backup_scripts).
Specifically `swift-backup-delete-old-data.sh` and `swift-backup-delete-old-SQL.sh` which call `deleteOldSwiftObjects.sh`. 
`deleteOldSwiftObjects.sh` deletes objects from the specified container that have reached the specified age.
`backup-apollos.sh` takes care of disk based backups, including deleting old archive files and SQL dumps.

**Comment by cat-bro** [comment]
At the moment the disk fills up and we lose backups unless someone logs in and manually deletes the files. A quick fix would be to try-catch the line that breaks it.

The impression I have gotten from talking to UW about plans for live replication (some time in the later half of the year) is that we could retire this script altogether. Replacing it might not be worth it at this point.

**Comment by jlqfab** [comment]
Fixes to slg.db-backup role merged into infrastructure repo: catch swift delete fails, correct template to match actual script and update crontab to run at 4am.

**Comment by cat-bro** [comment]
This issue can be closed thanks to @jlqfab's work
