### ISSUE TITLE
grafana on stats server needs stay at current version

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/infrastructure#1316]
the stats playbook has the issue that grafana will update with an apt update. The chosen grafana version in the host_vars/stats.usegalaxy.org.au is the one we want.

**Comment by jlqfab** [comment]
specify `grafana_version` in `host_vars/stats.usegalaxy.org.au.yml` so that the the default value `latest` for `cloudalchemy.grafana` isn't used.

**Comment by jlqfab** [comment]
see PR: [1319](https://github.com/usegalaxy-au/infrastructure/pull/1319)

**Comment by jlqfab** [comment]
follow up: also need to hold grafana at installed version. see PR's:
[ in stats_playbook.yml add a pre task to hold grafana package at curre… #1398 ](https://github.com/usegalaxy-au/infrastructure/pull/1398)
[ fix when condition for grafana install check to match yaml parser req… #1399 ](https://github.com/usegalaxy-au/infrastructure/pull/1399)
