### ISSUE TITLE
attached-volumes role needs safety checks

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/infrastructure#1318]
There is a problem with this set of tasks: https://github.com/usegalaxy-au/infrastructure/blob/master/roles/attached-volumes/tasks/set_up_volume.yml

If a volume is mounted at '/dev/vdb' with a filesystem and data, if a playbook is run with `{'device': /dev/vdb', 'partition': '1'}` in the attached_volumes variable, the task will start creating a partition of vdb and potentially damage the data already there.

Then `when` clause applied to creating a partition needs to prevent this.

**Comment by jlqfab** [comment]
See [PR 1366](https://github.com/usegalaxy-au/infrastructure/pull/1366l)

**Comment by jlqfab** [comment]
Improvements post merge of PR # 1366
- check how convert `num_parts` and `num_parts2` to int in `roles/attached-volumes/tasks/set_up_volume.yml` with something like: `num_parts: "{{ volume_info.partitions | length }}" | int`
- add options to mount or with default in `roles/attached-volumes/tasks/set_up_volume.yml` with something like:
   ```
      mount:

        :

        options: "{{ mount_options|d('defaults') }}"
```
