### ISSUE TITLE
Collect telegraf data from etca branch

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/infrastructure#1391]
- [x] Add a new db to influx called galaxy_etca using slg.influx_objects role
- [x] Update telegraf setting in group_vars/galaxy_etca.yml and uncomment
- [x] Uncomment telegraf role from etca playbooks

**Comment by jlqfab** [comment]
See PR: [Etca telegraf](https://github.com/usegalaxy-au/infrastructure/pull/1394)
