### ISSUE TITLE
Add galaxy-handlers to ETCA loads grafana page

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/infrastructure#1503]
Having load info for galaxy-handlers will be useful.

**Comment by jlqfab** [comment]
https://stats.usegalaxy.org.au/d/vr1lVme4z/etca-loads?orgId=1&refresh=10s&var-host=galaxy&var-host=galaxy-db&var-host=galaxy-job-nfs&var-host=galaxy-misc-nfs&var-host=galaxy-queue&var-host=galaxy-user-nfs&var-host=galaxy-handlers&var-hosts2=All&from=now-6h&to=now

**Comment by cat-bro** [comment]
galaxy-handlers is not selected by default when the page is loaded. If someone has to go and tick the box every time they go to that grafana page, this is not done.

**Comment by jlqfab** [comment]
galaxy-handlers has been added to the default hosts selected for the Main servers.

**Comment by cat-bro** [comment]
Thanks @jlqfab
