### ISSUE TITLE
AlphaFold disk space

### ISSUE THREAD

**Issue by neoformit** [usegalaxy-au/infrastructure#1527]
You may recall a ticket about an out-of-memory error on AlphaFold a few months back. Based on recent learnings it seems that AF2 should always have at least as much available scratch disk as it has memory. On our Azure nodes, we are currently at 60GB available disk with 100GB available mem. This likely explains this rare ticket - we can handle AF2 memory dumps of up 60GB but nothing more. It is possible (though apparently unusual) for AF2 to dump more that this to disk and thereby encounter the out-of-disk error.

**Action**: increase AF2's available scratch to 100GB to match the available RAM. This might be done by attaching a 120GB volume under `/scratch` and telling AF2 to write its temps here.

Based on feedback on DeepMind/AlphaFold Github:
https://github.com/google-deepmind/alphafold/issues/778#issuecomment-1632510909

**Comment by cat-bro** [comment]
Update on alphafold VM setup: the QLD VMs have /tmp space on the 2T volumes shared with job working directory space so this is unlikely to be a problem now
