### ISSUE TITLE
Cannot query db from psql shell on dev

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/infrastructure#17]
dev has postgres and a galaxy postgres user, and typing `\l` in the shell reveals that a db named `galaxy` does exist but I can't see the relations or tables for it.  It would be a good addition to the scripts to set this up properly.

**Comment by Slugger70** [comment]
This just requires the connection string to be stored in .pgpass in the user's home directory.

**Comment by cat-bro** [comment]
Closed with #79
